// Original A4 template. Coordinates use PDF points, measured from bottom left.
export const template = {
  id: 'legacy', name: 'SheetSmith Legacy · A4', width: 595.28, height: 841.89,
  portrait: { page: 0, x: 445, y: 611, width: 108, height: 133, mode: 'contain' },
  fields: [
    { name: 'CharacterName', path: 'identity.name', label: 'CHARACTER NAME', x: 42, y: 697, width: 380, height: 33 },
    { name: 'ClassLevel', path: 'classLevel', label: 'CLASS & LEVEL', x: 42, y: 651, width: 380, height: 28 },
    { name: 'Species', path: 'identity.species', label: 'SPECIES', x: 42, y: 599, width: 180, height: 28 },
    { name: 'Background', path: 'identity.background', label: 'BACKGROUND', x: 242, y: 599, width: 180, height: 28 },
    { name: 'PlayerName', path: 'identity.playerName', label: 'PLAYER NAME', x: 42, y: 547, width: 260, height: 28 },
    { name: 'Alignment', path: 'identity.alignment', label: 'ALIGNMENT', x: 442, y: 547, width: 111, height: 28 },
    { name: 'Proficiency', path: 'proficiencyBonus', label: 'PROFICIENCY', x: 322, y: 547, width: 100, height: 28, signed: true },
    ...['strength','dexterity','constitution','intelligence','wisdom','charisma'].map((key, index) => ({ name: key, path: `abilityDisplay.${key}`, label: key.slice(0,3).toUpperCase(), x: 42 + index * 86, y: 470, width: 78, height: 42 })),
    ...[['AC','combat.armourClass','ARMOUR CLASS'],['HP','combat.maxHP','MAX HP'],['Initiative','combat.initiative','INITIATIVE'],['Speed','combat.speed','SPEED (FT)'],['HitDice','combat.hitDice','HIT DICE'],['Passive','passivePerception','PASSIVE PERCEPTION']].map(([name,path,label], index) => ({ name,path,label,x:42+index*86,y:400,width:78,height:32 })),
    { name: 'Saves', path: 'saveDisplay', label: 'SAVING THROWS', x: 42, y: 248, width: 160, height: 118, multiline: true },
    { name: 'Skills', path: 'skillDisplay', label: 'SKILLS', x: 222, y: 99, width: 331, height: 267, multiline: true },
    { name: 'Attacks', path: 'attacks', label: 'ATTACKS / NOTES', x: 42, y: 99, width: 160, height: 120, multiline: true },
    { name: 'Equipment', path: 'equipment', label: 'EQUIPMENT', page: 1, x: 42, y: 427, width: 245, height: 298, multiline: true },
    { name: 'Traits', path: 'traits', label: 'PERSONALITY & BONDS', page: 1, x: 307, y: 427, width: 246, height: 298, multiline: true },
    { name: 'Currency', path: 'currency', label: 'COINS', page: 1, x: 42, y: 371, width: 511, height: 30 },
    { name: 'Features', path: 'features', label: 'FEATURES & TRAITS', page: 1, x: 42, y: 99, width: 511, height: 238, multiline: true },
    { name: 'Spells', path: 'spells', label: 'SPELLS / PREPARATION', page: 2, x: 42, y: 230, width: 511, height: 495, multiline: true },
    { name: 'SpellNotes', path: 'spellNotes', label: 'SPELLCASTING ABILITY / SAVE DC / ATTACK / SLOTS', page: 2, x: 42, y: 99, width: 511, height: 96, multiline: true },
  ],
};
